version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd bankchurn-api
            pip install -r requirements.txt
            pip install -r test_requirements.txt
      - run:
          name: Run tests
          command: |
            cd bankchurn-api
            python --version
            pip list
            echo "Current directory: $(pwd)"
            echo "Contents of current directory:"
            ls -la
            echo "Contents of app directory:"
            ls -la app/
            echo "Contents of app/tests directory:"
            ls -la app/tests/
            export PYTHONPATH=.
            export PYTHONHASHSEED=0
            echo "PYTHONPATH: $PYTHONPATH"
            python -m pytest app/tests/ -v
      - run:
          name: Run linting
          command: |
            cd bankchurn-api
            python -m flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
            python -m mypy app/ --ignore-missing-imports

  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: |
            curl -fsSL https://railway.com/install.sh | sh
            echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Deploy to Railway
          command: |
            cd bankchurn-api
            railway up --service=maiacicd --detach
          environment:
            RAILWAY_TOKEN: $RAILWAY_TOKEN

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
